CREATE DATABASE IF NOT EXISTS CAR_RENTAL_SERVICE;
USE CAR_RENTAL_SERVICE;

CREATE TABLE IF NOT EXISTS PRICE (
    PRICE_CODE 	INT PRIMARY KEY AUTO_INCREMENT,
    PRICE_DESCRIPTION VARCHAR(40),
    PRICE_RENTFEE NUMERIC(5 , 2 ) CHECK (PRICE_RENTFEE >= 0),
    PRICE_LATEFEE NUMERIC(5 , 2 ) CHECK (PRICE_LATEFEE >= 0)
);

CREATE TABLE IF NOT EXISTS VEHICLE_DETAILS (
    VEHICLE_CODE INT PRIMARY KEY AUTO_INCREMENT,
    VEHICLE_PASSENGERS NUMERIC(2 , 0 ) CHECK (VEHICLE_PASSENGERS >= 0),
    VEHICLE_SIZE VARCHAR(15),
    VEHICLE_AC BOOLEAN,
    VEHICLE_COLOR VARCHAR(20),
    VEHICLE_AUTOMATIC BOOLEAN,
    VEHICLE_BRAND VARCHAR(20),
    VEHICLE_MODEL VARCHAR(20),
    VEHICLE_YEAR NUMERIC(4 , 0 ),
    PRICE_CODE INT,
    FOREIGN KEY (PRICE_CODE)
        REFERENCES PRICE (PRICE_CODE)
);

CREATE TABLE IF NOT EXISTS CAR (
    CAR_CODE INT PRIMARY KEY AUTO_INCREMENT,
    VEHICLE_CODE INT,
    CAR_QUANTITY NUMERIC(3 , 0 ) CHECK (CAR_QUANTITY >= 0),
    FOREIGN KEY (VEHICLE_CODE)
        REFERENCES VEHICLE_DETAILS (VEHICLE_CODE)
);

CREATE TABLE IF NOT EXISTS CUSTOMER (
    CUSTOMER_ID INT PRIMARY KEY AUTO_INCREMENT,
    CUSTOMER_FNAME VARCHAR(30),
    CUSTOMER_LNAME VARCHAR(30),
    CUSTOMER_STREET VARCHAR(120),
    CUSTOMER_CITY VARCHAR(50),
    CUSTOMER_PROVINCE CHAR(2),
    CUSTOMER_POSTALCODE VARCHAR(7),
    CUSTOMER_BALANCE NUMERIC(10 , 2 )
);

CREATE TABLE IF NOT EXISTS RENTAL (
    RENTAL_NUMBER INT PRIMARY KEY AUTO_INCREMENT,
    RENTAL_DATE DATE,
    CUSTOMER_ID INT,
    FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUSTOMER (CUSTOMER_ID)
);


CREATE TABLE IF NOT EXISTS RENTAL_DETAILS (
    RENTAL_NUMBER INT,
    CAR_CODE INT,
    DETAIL_FEE NUMERIC(8 , 2 ),
    DETAIL_DUEDATE DATE,
    DETAIL_RETURNDATE DATE,
    DETAIL_LATEFEE NUMERIC(8 , 2 ),
    PRIMARY KEY (RENTAL_NUMBER , CAR_CODE),
    FOREIGN KEY (RENTAL_NUMBER)
        REFERENCES RENTAL (RENTAL_NUMBER),
    FOREIGN KEY (CAR_CODE)
        REFERENCES CAR (CAR_CODE)
);