INSERT INTO `VEHICLE_DETAILS` (`VEHICLE_PASSENGERS`, `VEHICLE_SIZE`, `VEHICLE_AC`, `VEHICLE_COLOR`, `VEHICLE_AUTOMATIC`, `VEHICLE_BRAND`, `VEHICLE_MODEL`, `VEHICLE_YEAR`, `PRICE_CODE`) 
VALUES (4, 'Coupe', 1, 'Orange', 1, 'BMW', 'M4', '2016', '04');

INSERT INTO `VEHICLE_DETAILS` (`VEHICLE_PASSENGERS`, `VEHICLE_SIZE`, `VEHICLE_AC`, `VEHICLE_COLOR`, `VEHICLE_AUTOMATIC`, `VEHICLE_BRAND`, `VEHICLE_MODEL`, `VEHICLE_YEAR`, `PRICE_CODE`) 
VALUES (4, 'Sedan', 1, 'Red', 1, 'BMW', 'M3', '2014', '04');

INSERT INTO `VEHICLE_DETAILS` (`VEHICLE_PASSENGERS`, `VEHICLE_SIZE`, `VEHICLE_AC`, `VEHICLE_COLOR`, `VEHICLE_AUTOMATIC`, `VEHICLE_BRAND`, `VEHICLE_MODEL`, `VEHICLE_YEAR`, `PRICE_CODE`) 
VALUES (2, 'Convertible', 1, 'White', 0, 'Mercedes-Benz', 'SL400 Roadster', '2016', '04');

INSERT INTO `VEHICLE_DETAILS` (`VEHICLE_PASSENGERS`, `VEHICLE_SIZE`, `VEHICLE_AC`, `VEHICLE_COLOR`, `VEHICLE_AUTOMATIC`, `VEHICLE_BRAND`, `VEHICLE_MODEL`, `VEHICLE_YEAR`, `PRICE_CODE`) 
VALUES (4, 'Sedan', 1, 'Black', 1, 'Rolls-Royce', 'Phantom', '2012', '05');

INSERT INTO `VEHICLE_DETAILS` (`VEHICLE_PASSENGERS`, `VEHICLE_SIZE`, `VEHICLE_AC`, `VEHICLE_COLOR`, `VEHICLE_AUTOMATIC`, `VEHICLE_BRAND`, `VEHICLE_MODEL`, `VEHICLE_YEAR`, `PRICE_CODE`) 
VALUES (4, 'Coupe', 1, 'Black', 1, 'Rolls-Royce', 'Wraith', '2015', '05');

INSERT INTO `VEHICLE_DETAILS` (`VEHICLE_PASSENGERS`, `VEHICLE_SIZE`, `VEHICLE_AC`, `VEHICLE_COLOR`, `VEHICLE_AUTOMATIC`, `VEHICLE_BRAND`, `VEHICLE_MODEL`, `VEHICLE_YEAR`, `PRICE_CODE`) 
VALUES (2, 'Coupe', 1, 'Red', 1, 'Ferrari', 'LaFerrari', '2016', '05');

INSERT INTO `VEHICLE_DETAILS` (`VEHICLE_PASSENGERS`, `VEHICLE_SIZE`, `VEHICLE_AC`, `VEHICLE_COLOR`, `VEHICLE_AUTOMATIC`, `VEHICLE_BRAND`, `VEHICLE_MODEL`, `VEHICLE_YEAR`, `PRICE_CODE`) 
VALUES (2, 'Coupe', 1, 'Yellow', 0, 'Aston Martin', 'Vantage', '2013', '04');

INSERT INTO `VEHICLE_DETAILS` (`VEHICLE_PASSENGERS`, `VEHICLE_SIZE`, `VEHICLE_AC`, `VEHICLE_COLOR`, `VEHICLE_AUTOMATIC`, `VEHICLE_BRAND`, `VEHICLE_MODEL`, `VEHICLE_YEAR`, `PRICE_CODE`) 
VALUES (2, 'Coupe', 1, 'Blue', 1, 'Lamborghini', 'Aventador', '2015', '05');

INSERT INTO `VEHICLE_DETAILS` (`VEHICLE_PASSENGERS`, `VEHICLE_SIZE`, `VEHICLE_AC`, `VEHICLE_COLOR`, `VEHICLE_AUTOMATIC`, `VEHICLE_BRAND`, `VEHICLE_MODEL`, `VEHICLE_YEAR`, `PRICE_CODE`) 
VALUES (4, 'Sedan', 1, 'Black', 1, 'Bentley', 'Mulsanne', '2016', '05');

INSERT INTO `VEHICLE_DETAILS` (`VEHICLE_PASSENGERS`, `VEHICLE_SIZE`, `VEHICLE_AC`, `VEHICLE_COLOR`, `VEHICLE_AUTOMATIC`, `VEHICLE_BRAND`, `VEHICLE_MODEL`, `VEHICLE_YEAR`, `PRICE_CODE`) 
VALUES (4, 'Convertible', 1, 'Red', 1, 'Maserati', 'GranTurismo', '2012', '05');

INSERT INTO `VEHICLE_DETAILS` (`VEHICLE_PASSENGERS`, `VEHICLE_SIZE`, `VEHICLE_AC`, `VEHICLE_COLOR`, `VEHICLE_AUTOMATIC`, `VEHICLE_BRAND`, `VEHICLE_MODEL`, `VEHICLE_YEAR`, `PRICE_CODE`) 
VALUES (4, 'Sedan', 1, 'Red', 0, 'BMW', 'M6', '2014', '05');