INSERT INTO `PRICE` (`PRICE_DESCRIPTION`, `PRICE_RENTFEE`, `PRICE_LATEFEE`) VALUES 
('Basic', 25, 25);
INSERT INTO `PRICE` (`PRICE_DESCRIPTION`, `PRICE_RENTFEE`, `PRICE_LATEFEE`) VALUES 
('Economy', 50, 30);
INSERT INTO `PRICE` (`PRICE_DESCRIPTION`, `PRICE_RENTFEE`, `PRICE_LATEFEE`) VALUES 
('Standard', 75, 35);
INSERT INTO `PRICE` (`PRICE_DESCRIPTION`, `PRICE_RENTFEE`, `PRICE_LATEFEE`) VALUES 
('Premium', 100, 40);
INSERT INTO `PRICE` (`PRICE_DESCRIPTION`, `PRICE_RENTFEE`, `PRICE_LATEFEE`) VALUES 
('Ultimate', 200, 50);
