INSERT INTO `CUSTOMER` (`CUSTOMER_FNAME`, `CUSTOMER_LNAME`, `CUSTOMER_STREET`, `CUSTOMER_CITY`, `CUSTOMER_PROVINCE`, `CUSTOMER_POSTALCODE`, `CUSTOMER_BALANCE`) 
VALUES ('Timothy', 'Thompson', '25 South Street', 'Halifax', 'NS', 'B0B 0B0', '0');
INSERT INTO `CUSTOMER` (`CUSTOMER_FNAME`, `CUSTOMER_LNAME`, `CUSTOMER_STREET`, `CUSTOMER_CITY`, `CUSTOMER_PROVINCE`, `CUSTOMER_POSTALCODE`, `CUSTOMER_BALANCE`) 
VALUES ('Drake', 'Golfer', '409 Forward Crescent', 'Bedford', 'NS', 'B1B 1B1', '500');
INSERT INTO `CUSTOMER` (`CUSTOMER_FNAME`, `CUSTOMER_LNAME`, `CUSTOMER_STREET`, `CUSTOMER_CITY`, `CUSTOMER_PROVINCE`, `CUSTOMER_POSTALCODE`, `CUSTOMER_BALANCE`) 
VALUES ('Fredrick', 'MacDougall', '823 Crabdale Avenue', 'Truro', 'NS', 'B9L 4T9', '0');
INSERT INTO `CUSTOMER` (`CUSTOMER_FNAME`, `CUSTOMER_LNAME`, `CUSTOMER_STREET`, `CUSTOMER_CITY`, `CUSTOMER_PROVINCE`, `CUSTOMER_POSTALCODE`, `CUSTOMER_BALANCE`) 
VALUES ('Tracy', 'Foxton', '535 Forkspoon Lane', 'Moncton', 'NB', 'C3T 2Y3', '1000');
INSERT INTO `CUSTOMER` (`CUSTOMER_FNAME`, `CUSTOMER_LNAME`, `CUSTOMER_STREET`, `CUSTOMER_CITY`, `CUSTOMER_PROVINCE`, `CUSTOMER_POSTALCODE`, `CUSTOMER_BALANCE`) 
VALUES ('Taylor', 'Erikson', '190 Keltic Drive', 'Sydney River', 'NS', 'B4L 9C2', '0');
INSERT INTO `CUSTOMER` (`CUSTOMER_FNAME`, `CUSTOMER_LNAME`, `CUSTOMER_STREET`, `CUSTOMER_CITY`, `CUSTOMER_PROVINCE`, `CUSTOMER_POSTALCODE`, `CUSTOMER_BALANCE`) 
VALUES ('Robert', 'Chang', '122 Main Street', 'Glace Bay', 'NS', 'C2B 5B2', '0');
INSERT INTO `CUSTOMER` (`CUSTOMER_FNAME`, `CUSTOMER_LNAME`, `CUSTOMER_STREET`, `CUSTOMER_CITY`, `CUSTOMER_PROVINCE`, `CUSTOMER_POSTALCODE`, `CUSTOMER_BALANCE`) 
VALUES ('Sarah', 'Goode', '708 Fairview Road', 'Yarmouth', 'NS', 'Y6T 3B6', '250');


